name: Push to Master

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.os }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true
     
      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Install Strace
        run: sudo apt-get update && sudo apt-get install -y strace

      - name: Run integration tests with strace
        run: strace -o strace_logs.txt cea test --type integration
          
      - name: Show environment info
        run: |
            echo "Current directory: $(pwd)"
            echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
            ls -lah   

      - name: Upload strace artifacts
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs.txt

