name: Push to Master

on:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Install Strace (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y strace

      - name: Run tests
        shell: bash -l {0}
        run: |
          cea test --type integration
