name: Push to Master

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.os }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup strace environment
        run: |
          chmod +x ./strace-wrapper.sh
          ./strace-wrapper.sh
          chmod +x ./strace_run.sh

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true

      - name: Install CEA (with strace)
        shell: bash -l {0}
        run: |
          ./strace_run.sh install_cea "pip install ."

      - name: Run unittest (with strace)
        shell: bash -l {0}
        run: |
          ./strace_run.sh unittest "cea test --type unittest"

      - name: Run integration tests (with strace)
        shell: bash -l {0}
        run: |
          ./strace_run.sh integration "cea test --type integration"

      - name: Upload all strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs_${{ github.job }}
          path: artifact_upload/
