name: Push to Master

on:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }}-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true

      - name: Install CEA
        shell: bash -l {0}
        run: pip install .

      - name: Install Strace (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y strace

      - name: Run integration test with trace (Linux only)
        if: runner.os == 'Linux'
        uses: ./.github/trace-step
        with:
          step-name: integration
          command: "cea test --type integration"

      - name: Upload strace logs (Linux only)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: strace-logs-${{ matrix.os }}
          path: strace_logs/
