name: Pull Request Tests
on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]
jobs:
  check_environment_yml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup master branch locally without switching current branch
        run: "mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step1.log bash -c \"|\"\n        mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step1.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step1.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step1.log bash -c \"|\"\n            mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step1.log bash -c \"|\"\n          mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step1.log bash -c \"|\"\n      mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step1.log bash -c \"git fetch origin master:master\"\n    EOF\n    \n    EOF\n    \n      EOF\n      \n      EOF\n      \n      EOF\n      "
      - name: Check environment.yml diff
        id: environment_yml_diff
        run: "mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step2.log bash -c \"|\"\n        mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step2.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step2.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step2.log bash -c \"|\"\n            mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step2.log bash -c \"|\"\n          mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step2.log bash -c \"|\"\n      mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step2.log bash -c \"set +e\ngit diff --quiet ..master -- environment.yml\necho \"env_diff=$?\" >> \"$GITHUB_OUTPUT\"\"\n    EOF\n    \n    EOF\n    \n      EOF\n      \n      EOF\n      \n      EOF\n      "
      - name: Check conda-lock.yml diff
        id: conda_lock_yml_diff
        run: "mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step3.log bash -c \"|\"\n        mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step3.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step3.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step3.log bash -c \"|\"\n            mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step3.log bash -c \"|\"\n          mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step3.log bash -c \"|\"\n      mkdir -p strace_logs && strace -tt -f -o strace_logs/check_environment_yml_step3.log bash -c \"set +e\ngit diff --quiet ..master -- conda-lock.yml\necho \"lock_diff=$?\" >> \"$GITHUB_OUTPUT\"\"\n    EOF\n    \n    EOF\n    \n      EOF\n      \n      EOF\n      \n      EOF\n      "
      - uses: actions/github-script@v7
        if: ${{ steps.environment_yml_diff.outputs.env_diff != 0 && steps.conda_lock_yml_diff.outputs.lock_diff == 0 }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Changes detected in `environment.yml` but `conda-lock.yml` is not updated.'
            })
            core.setFailed('conda-lock.yml needs to be updated')
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: check_environment_yml
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda-lock.yml
          environment-name: cea
          cache-environment: true
      - name: Install CEA
        shell: bash -l {0}
        run: mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step2.log bash -c "pip install ."
      - name: Run tests
        shell: bash -l {0}
        run: "mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"|\"\n        mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"|\"\n              mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"|\"\n            mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"|\"\n          mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"|\"\n          mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"|\"\n      mkdir -p strace_logs && strace -tt -f -o strace_logs/build_step3.log bash -c \"cea test --type unittest\ncea test --type integration\"\n    EOF\n    \n    EOF\n    \n    EOF\n    \n      EOF\n      \n      EOF\n      \n      EOF\n      "
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
    steps:
      - name: Upload strace logs
        uses: actions/upload-artifact@v4
        with:
          name: strace_logs
          path: strace_logs/
